### ISSUE TITLE
关于loadmore没有触发的问题：

### ISSUE THREAD

**Issue by Steamed-fish** [AwesomeDevin/vue-waterfall2#145]
场景：
我在首页使用了vue-waterfall2 版本是1.10.6，执行上拉刷新加载数据正常，但是点击进入到商品详情页后（或者跳转其他页面）再返回时，再进行上拉刷新时loadmore没有触发，目前还不清楚原因

**Comment by AwesomeDevin** [comment]
😂 可能需要提供一个demo才行，没有没有复现类似的问题

**Comment by Steamed-fish** [comment]
> 😂 可能需要提供一个demo才行，没有没有复现类似的问题

https://shop3.0.azambe.com/categoryDetail?id=289&name=Sandles
这是我的测试demo，上面的场景问题，只有刷新页面才能再继续上拉加载数据，这个项目中有多个页面使用了该瀑布流组件，当前页面组件出了上述的问题，不影响其他页面的瀑布流加载，但只要其他页面也进行上述场景操作，同样出现loadmore无法触发问题

**Comment by AwesomeDevin** [comment]
我跟一下---- Replied Message ***@***.***>Date11/07/2023 17:03 ***@***.***> CcDevin ***@***.***>***@***.***>SubjectRe: [AwesomeDevin/vue-waterfall2] 关于loadmore没有触发的问题： (Issue #145)

 可能需要提供一个demo才行，没有没有复现类似的问题

https://shop3.0.azambe.com/categoryDetail?id=289&name=Sandles
这是我的测试demo，上面的场景问题，只有刷新页面才能再继续上拉加载数据，这个项目中有多个页面使用了该瀑布流组件，当前页面组件出了上述的问题，不影响其他页面的瀑布流加载，但只要其他页面也进行上述场景操作，同样出现loadmore无法触发问题

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/AwesomeDevin/vue-waterfall2/issues/145#issuecomment-1798079529",
"url": "https://github.com/AwesomeDevin/vue-waterfall2/issues/145#issuecomment-1798079529",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AwesomeDevin** [comment]
请问是使用了keep-alive吗

**Comment by AwesomeDevin** [comment]
我试了一下，好像是要上拉幅度比较大才能触发loadmore，可以试试修改loadDistance这个参数

**Comment by Steamed-fish** [comment]
是的，返回时waterfall.vue的mounted没有触发

**Comment by Steamed-fish** [comment]
loadDistance我改过，目前是100，进入详情页返回后跟loadDistance没关系

**Comment by Steamed-fish** [comment]
请问作者大大关于使用keep-alive包裹路由使用vue-waterfall2，应该如何解决这种问题

**Comment by AwesomeDevin** [comment]
我调试一下看看

**Comment by AwesomeDevin** [comment]
> 我调试一下看看

<img width="374" alt="image" src="https://github.com/AwesomeDevin/vue-waterfall2/assets/22369504/1735bbfa-52c7-4056-b910-a8c0d3f8ef92">
你好，我本地调试了一下，添加 keep-alive 也是可以触发loadmore的，请问你是用的哪个版本

**Comment by AwesomeDevin** [comment]
![image](https://github.com/AwesomeDevin/vue-waterfall2/assets/22369504/77082658-fd14-42d7-a9c0-adc3935ab75a)
另外可以尝试一下监听scroll, 获取滚动事件的相关信息，排查一下原因

**Comment by AwesomeDevin** [comment]
> loadDistance可以改大一点试试

**Comment by Steamed-fish** [comment]
已更新1.10.7版本，目前已解决问题，感谢作者大大
